[package]
name = "desktop"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
tauri = { version = "1", features = [] }
[build-dependencies]
tauri-build = { version = "1", features = [] }


